### ISSUE TITLE
为什么还要后端套模板

### ISSUE THREAD

**Issue by nimoc** [xuexb/apijs#1]
> 开发的js里接口url使用/api/{类别}/{行为}的绝对路径，本地依赖apijs模拟的数据来测试，当测试没问题后把文件推送到内网的测试环境，并通知后端**套模板**

apijs 是否是个 mockserver？ 如果是 为什么要让后端"套模板"。mock server 应该允许前端在本地编写后端模板

**Comment by xuexb** [comment]
> 首先是其定位，见：#2 

其实早期在我前端开发中不想过多的因为`数据`而影响进度，后来经过一段`面向接口`式的开发，我发现**文档**着实重要，于是我就在想如果很好的维护`接口`和`文档`呢，于是我想让其关联，这样以后修改一处即可生效～

后来引入`mockjs`的语法后可以生成几乎任何想要的数据结构，然后需要配置下文件的数组从而生成按`类目`的文档标题。当然这块我接下来要想想如何更好的语义化的配置。

而至于`为什么还要后端套模板`，这个因项目的差异，和后端框架的多元化，我不想过多的干涉后端渲染的逻辑，比如后端使用了一些几乎本地不能运行的`lib`，或者说有强依赖的`layout`。

当然我现在还做着**套模板**的任务，不过这是同步的数据，而`apijs`是处理异步的数据。

当然`apijs`应该不会满足多数的前端模式需求，不过我认为这是一种思路吧，我曾找过很多人了解他们是如何处理异步数据，得到的结论大多是自己写`*.json`文件，我认为这样不太帅～

而从我认识`apijs`的方式后我就使用这种形式来开发、自测，多状态、多形式的返回值可以使我的代码更健壮，所以我一点一点写下了这个代码～
